name: Push main
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main
    paths-ignore:
      - 'tmp/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          create_annotated_tag: true
          github_token: ${{ secrets.RELEASE_TOKEN }}
      - name: save changelog
        run: echo ${{ steps.tag_version.outputs.changelog }} > tmp/changelog.txt