name: Publish artifact to releases.
#on:
#  release:
#    types: [created]

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build package
        env:
          USENAME: ${{github.actor}}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode clean package --settings settings.xml
      - name: Read changelog file
        id: changelog
        run: echo "::set-output name=body::$(cat tmp/changelog.txt)"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.body }}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: target/reporte-nomina.jar
