name: Publish package to GitHub Packages
#on:
#  release:
#    types: [created]
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build package
        env:
          USENAME: ${{github.actor}}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode clean package --settings settings.xml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/reporte-nomina.jar
